### ISSUE TITLE
compatability problems with version 5.0.2

### ISSUE THREAD

**Issue by albenik85** [nanego/redmine_datetime_custom_field#23]
Hi all,

I just updated my redmine installation to version 5.0.2 and it seems like this plugin is not compatible with it. 
bundle install was succesfull but during db migration I received
"LoadError: cannot load such file -- redmine_datetime_custom_field/hooks"

Was anybody able to use this plugin with 5.0.x already?

**Comment by nanego** [comment]
Hello,
I wanted to inform you that I have made updates to the plugin, and it should now be fully compatible with both Redmine 5 and Redmine 4.
Could you try out the latest version and provide confirmation that everything is functioning as it did before? Thank you

**Comment by serhiyraskoley** [comment]
Hi guys.

I tried your plugin today and it doesn't work for my version.

Here is some additional information.
```
Environment:
  Redmine version                5.1.1.stable
  Ruby version                   3.2.0-p0 (2022-12-25) [x86_64-linux]
  Rails version                  6.1.7.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
  Redmine settings:
  Redmine theme                  Purplemine (includes JavaScript)
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  redmine_base_deface            5.1.1
  redmine_datetime_custom_field  3.3.0
  view_customize                 3.5.1
```

I add two custom fields for testing. The date and time are visible to me and I can select them.
![image](https://github.com/jbbarth/redmine_base_deface/assets/22105624/a1f7edf2-81e8-405a-8f01-a0b4fb499bd3)

When I submit my task, I get an error from apache.
![image](https://github.com/jbbarth/redmine_base_deface/assets/22105624/713a1a90-0401-4f2b-8b4c-2cc4d4de3d4f)

```
I, [2024-03-15T12:44:47.114587 #28723]  INFO -- : [e66862fd-a18b-4926-a7f9-33b719b4c2f6]   Current user: user1 (id=481)
I, [2024-03-15T12:44:47.280746 #28723]  INFO -- : [e66862fd-a18b-4926-a7f9-33b719b4c2f6]   Rendered issues/new.html.erb within layouts/base (Duration: 69.1ms | Allocations: 14697)
I, [2024-03-15T12:44:47.336135 #28723]  INFO -- : [e66862fd-a18b-4926-a7f9-33b719b4c2f6]   Rendered layout layouts/base.html.erb (Duration: 124.6ms | Allocations: 28766)
I, [2024-03-15T12:44:47.336882 #28723]  INFO -- : [e66862fd-a18b-4926-a7f9-33b719b4c2f6] Completed 200 OK in 239ms (Views: 91.5ms | ActiveRecord: 64.8ms | Allocations: 56421)
I, [2024-03-15T12:44:50.329855 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03] Started POST "/projects/test-project-for-me/issues" for 192.168.154.1 at 2024-03-15 12:44:50 +0200
I, [2024-03-15T12:44:50.331009 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03] Processing by IssuesController#create as HTML
I, [2024-03-15T12:44:50.331196 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03]   Parameters: {"utf8"=>"?", "authenticity_token"=>"GOyYIxBi3psLYzwSquqvsyREGSgYawqizgvCLsF640qu3L81JyC2arwGutMQXvMYWzpRjFyu/0c2yGav2RATCw==", "form_update_triggered_by"=>"", "issue"=>{"tracker_id"=>"171", "subject"=>"123123", "status_id"=>"18", "priority_id"=>"2", "assigned_to_id"=>"481", "start_date"=>"2024-03-15", "estimated_hours"=>"", "custom_field_values"=>{"167"=>"15/03/2024 12:43", "168"=>"22/03/2024 12:44"}, "watcher_user_ids"=>[""]}, "was_default_status"=>"18", "commit"=>"????????", "project_id"=>"test-project-for-me"}
I, [2024-03-15T12:44:50.339569 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03]   Current user: user1 (id=481)
I, [2024-03-15T12:44:50.467200 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03] Redirected to http://192.168.154.128/issues/90175
I, [2024-03-15T12:44:50.467690 #28723]  INFO -- : [4781585d-1b91-478f-945d-6ce9c2117a03] Completed 302 Found in 136ms (ActiveRecord: 40.9ms | Allocations: 31097)
I, [2024-03-15T12:44:50.479138 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017] Started GET "/issues/90175" for 192.168.154.1 at 2024-03-15 12:44:50 +0200
I, [2024-03-15T12:44:50.480607 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017] Processing by IssuesController#show as HTML
I, [2024-03-15T12:44:50.480738 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017]   Parameters: {"id"=>"90175"}
I, [2024-03-15T12:44:50.489158 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017]   Current user: user1 (id=481)
I, [2024-03-15T12:44:50.661806 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017]   Rendered issues/show.html.erb within layouts/base (Duration: 42.5ms | Allocations: 6278)
I, [2024-03-15T12:44:50.662082 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017]   Rendered layout layouts/base.html.erb (Duration: 42.8ms | Allocations: 6306)
I, [2024-03-15T12:44:50.662430 #28723]  INFO -- : [ea31584e-87a6-4b56-b12f-2ef800213017] Completed 500 Internal Server Error in 182ms (ActiveRecord: 55.8ms | Allocations: 30375)
F, [2024-03-15T12:44:50.663685 #28723] FATAL -- : [ea31584e-87a6-4b56-b12f-2ef800213017]
[ea31584e-87a6-4b56-b12f-2ef800213017] ActionView::Template::Error (wrong number of arguments (given 2, expected 1)):
[ea31584e-87a6-4b56-b12f-2ef800213017]     77:     rows.right l(:label_spent_time), issue_spent_hours_details(@issue), :class => 'spent-time'
[ea31584e-87a6-4b56-b12f-2ef800213017]     78:   end
[ea31584e-87a6-4b56-b12f-2ef800213017]     79: end %>
[ea31584e-87a6-4b56-b12f-2ef800213017]     80: <%= render_half_width_custom_fields_rows(@issue) %>
[ea31584e-87a6-4b56-b12f-2ef800213017]     81: <%= call_hook(:view_issues_show_details_bottom, :issue => @issue) %>
[ea31584e-87a6-4b56-b12f-2ef800213017]     82: </div>
[ea31584e-87a6-4b56-b12f-2ef800213017]     83:
[ea31584e-87a6-4b56-b12f-2ef800213017]
[ea31584e-87a6-4b56-b12f-2ef800213017] plugins/redmine_datetime_custom_field/lib/redmine_datetime_custom_field/application_helper_patch.rb:40:in `format_time_without_zone'
[ea31584e-87a6-4b56-b12f-2ef800213017] plugins/redmine_datetime_custom_field/lib/redmine_datetime_custom_field/application_helper_patch.rb:17:in `format_object'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/custom_fields_helper.rb:167:in `show_value'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/custom_fields_helper.rb:156:in `custom_field_value_tag'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:379:in `block (2 levels) in render_half_width_custom_fields_rows'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:377:in `each'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:377:in `each_with_index'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:377:in `block in render_half_width_custom_fields_rows'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:367:in `issue_fields_rows'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/helpers/issues_helper.rb:376:in `render_half_width_custom_fields_rows'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/views/issues/show.html.erb:80:in `_b90fe418574b09ef2de15efe30adf4c5'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/controllers/issues_controller.rb:118:in `block (2 levels) in show'
[ea31584e-87a6-4b56-b12f-2ef800213017] app/controllers/issues_controller.rb:110:in `show'
[ea31584e-87a6-4b56-b12f-2ef800213017] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

😶‍🌫️

**Comment by nanego** [comment]
Hello. I have just updated the plugin to fix this issue, and enhance compatibility with Redmine 5.1.

**Comment by serhiyraskoley** [comment]
Hello @nanego.

Thanks for your quickly response and fix issue.

I just tested on 
```
Environment:
  Redmine version                5.1.1.stable
  Ruby version                   3.2.0-p0 (2022-12-25) [x86_64-linux]
  Rails version                  6.1.7.6
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Purplemine (includes JavaScript)
SCM:
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  custom_avatar                  0.0.1
  redmine_base_deface            5.1.1
  redmine_datetime_custom_field  3.3.0
  view_customize                 3.5.1
``` 

Everything works fine. 

I created custom field **1**.

Here development logs

[development.log](https://github.com/nanego/redmine_datetime_custom_field/files/14773078/development.log)

**Comment by KrishGopalakrishnan** [comment]
Hope this will work 5.1.3 release

**Comment by nanego** [comment]
The plugin is currently compatible with the latest Redmine versions. I’m closing this issue.

**Comment by KrishGopalakrishnan** [comment]
> The plugin is currently compatible with the latest Redmine versions. I’m closing this issue.

Thank you for your confirmation
